### PR TITLE
hostApiBranch Review

### PR DESCRIPTION
**Pull request by EMurtaghh**
hostAPiBranch completed, all relevant hostApi cards finished and ready for Sprint Review tomorrow.

### CODE REVIEW

**Comment by JohnHunter809** [comment]
Good job! very thorough testing

**Comment by pmank64** [comment]
Looks great, implementation is very well done.

**Comment by EMurtaghh** [comment]
Branch Merged. Branch deleted.

**Comment by EMurtaghh** [comment]
Branch merged!

**Pull request merged**
