### PR TITLE
Load stock from file branch

### PR DESCRIPTION
**Pull request by JohnHunter809**

### CODE REVIEW

**Comment by JohnHunter809** [comment]
Stock can now load ingredients from a file, handles bad files and nonexistent file names. Tests reflect this and pass

**Comment by pmank64** [comment]
Looks great! We just need to make sure we are testing for when an item being added from a file already exists, especially if the cost is different.

**Comment by EMurtaghh** [comment]
Looks good, codebase makes sense and tests cover a wide range of issues that could be present in the implementation. Got an a-okay from me!

**Comment by averma1** [comment]
Looks good!  We might have a problem with the Circleci folder.  But other than that, I think the tests look thorough.  Really cool stuff with the file too, and well documented so I know what I'm looking at.  I'd say we're ready!

**Comment by CryptoGraphicDragon** [comment]
Looking good! Might need to fix the Circleci stuff, but the all the functions and tests are great.

**Pull request closed without merging**
